#! /bin/bash

#constraintsType="homogeneous"
constraintsType="fixedDetectors"

# True/False
resolveRotZ="False"

iterations=1

useExtendedConstraintsForHigherIterations="y"

#-------------------------------------

optStr="s"
if [ $resolveRotZ == "True" ]
then
  optStr="sr"
fi

tag=""
if [ $useExtendedConstraintsForHigherIterations != "y" ]
then
	tag="basic"	
else
	tag="extended"	
fi

analysisDir="analysis/$optStr.$constraintsType.$tag"
resultDir="results/$optStr.$constraintsType.$tag"
plotsDir="plots/$optStr.$constraintsType.$tag"

{
	echo "#! /bin/bash"
	echo ""
	echo "function runDP()"
	echo "{"
	echo "	echo \"* $analysisDir/\$1\""
	echo "	cd $analysisDir/\$1"
	echo "	cmsRun TestBeamAlignment_cfg.py &> log"
	echo "	cd - > /dev/null"
	echo "}"
	echo ""
} > runIt

mkdir -p "$resultDir"
mkdir -p "$plotsDir"

for dp in `seq 12`
do
	mkdir -p "$analysisDir/DP$dp/optical"
	
	if [ $useExtendedConstraintsForHigherIterations != "y" ]
	then
		useExtendedConstraints="False"
	else
		useExtendedConstraints="True"
	fi

	misalignedString=""
	opticalFile="$CMSSW_BASE/src/TotemAlignment/RPData/Optical/DP${dp}.xml"
	if [ -f "$opticalFile" ]
	then
		misalignedString=", MisalignedFile = cms.string('$opticalFile')"
	fi

	cat template_cfg.py|sed "\
		s|\$algorithms|'Ideal'|; \
		s|\$emptySource|True|; \
		s|\$testbeamData|testbeam_data_pot${dp}_cff|; \
		s|\$misalignedString|$misalignedString|; \
		s|\$realString||; \
		s|\$constraintsType|$constraintsType|; \
		s|\$useExtendedConstraints|$useExtendedConstraints|; \
		s|\$resolveShR|True|; \
		s|\$resolveRotZ|$resolveRotZ|; \
			" > "$analysisDir/DP$dp/optical/TestBeamAlignment_cfg.py"
	
	echo "runDP DP${dp}/optical" >> runIt

	for i in `seq $iterations`
	do
		#echo $dp $i

		mkdir -p "$analysisDir/DP$dp/iteration$i"
	
		realString=""
		useExtendedConstraints="True"
		if [ $i -gt 1 ]
		then
			let p=i-1
			cwd=`pwd`
			realString=", RealFile = cms.string('$cwd/$analysisDir/DP$dp/iteration$p/cumulative_Jan.xml')"

			if [ $useExtendedConstraintsForHigherIterations != "y" ]
			then
				useExtendedConstraints="False"
			fi
		fi
	
		cat template_cfg.py|sed "\
			s|\$algorithms|'Jan'|; \
			s|\$emptySource|False|; \
			s|\$testbeamData|testbeam_data_pot${dp}_cff|; \
			s|\$realString|$realString|; \
			s|\$misalignedString||; \
			s|\$constraintsType|$constraintsType|; \
			s|\$useExtendedConstraints|$useExtendedConstraints|; \
		    s|\$resolveShR|True|; \
		    s|\$resolveRotZ|$resolveRotZ|; \
				" > "$analysisDir/DP$dp/iteration$i/TestBeamAlignment_cfg.py"
	
		echo "runDP DP${dp}/iteration${i}" >> runIt
	done
done

chmod +x runIt
