import FWCore.ParameterSet.Config as cms

#ideal geometry
XMLIdealGeometryESSource = cms.ESSource("XMLIdealGeometryESSource",
    geomXMLFiles = cms.vstring('Geometry/CMSCommonData/data/materials.xml', 
        'Geometry/CMSCommonData/data/rotations.xml', 
        'Geometry/TotemRPData/data/RP_Materials.xml', 
        'Geometry/TotemRPData/data/RP_Transformations.xml', 
        'Geometry/CMSCommonData/data/normal/cmsextent.xml', 
        'Geometry/TotemRPData/data/TotemRPGlobal.xml', 
        'Geometry/CMSCommonData/data/cms.xml', 
        'Geometry/TotemRPData/data/RP_Materials.xml', 
        'Geometry/TotemRPData/data/RP_Transformations.xml', 
        'Geometry/TotemRPData/data/RP_Device.xml', 
        'Geometry/TotemRPData/data/RP_Vertical_Device.xml', 
        'Geometry/TotemRPData/data/RP_Horizontal_Device.xml', 
        'Geometry/TotemRPData/data/RP_Box.xml', 
        'Geometry/TotemRPData/data/RP_Box/RP_Box_000.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_001.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_002.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_003.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_004.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_005.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_020.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_021.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_022.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_023.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_024.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_025.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_100.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_101.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_102.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_103.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_104.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_105.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_120.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_121.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_122.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_123.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_124.xml',
        'Geometry/TotemRPData/data/RP_Box/RP_Box_125.xml', 
        'Geometry/TotemRPData/data/RP_Hybrid.xml', 
        'Geometry/TotemRPData/data/TwoRPTestBeam/RP_Detectors_Assembly.xml', 
        'Geometry/TotemRPData/data/TwoRPTestBeam/RP_Stations_Assembly.xml', 
        'Geometry/TotemRPData/data/TwoRPTestBeam/RP_220_Right_Station.xml'),
    rootNodeName = cms.string('TotemRPGlobal:OTOTEM')
)

# real geometry
TotemRPGeometryESModule = cms.ESProducer("TotemRPGeometryESModule")
