import FWCore.ParameterSet.Config as cms

generator = cms.EDFilter("SherpaGeneratorFilter",
	maxEventsToPrint = cms.int32(0),
	libDir = cms.untracked.string('SherpaTmp'),
	SherpaParameters = cms.PSet(
		parameterSets = cms.vstring('Run'),
		Run = cms.vstring('# steering file based on example from Sherpa 1.2.3 distribution:',
			'#   share/SHERPA-MC/Examples/Tevatron_UE/Run.dat',
			'(run){',
			'  # disable colorizing of text printed on screen:',
			'  #PRETTY_PRINT = Off',
			'  ',
			'  # number of events:',
			'  EVENTS = 10000',
			'  ',
			'  # set random seed:',
			'  # (see section "6.1.3 RANDOM_SEED" of Sherpa manual for details)',
			'  RANDOM_SEED = 1828 9',
			'  ',
			'  # Event output file:',
			'  #HEPMC2_GENEVENT_OUTPUT = sherpa',
			'  # full name of output file will be:',
			'  #  "sherpa.hepmc2g"',
			'  EVENT_MODE = HepMC',
			'	 HEPMC_OUTPUT = abc',
			'  ',
			'  # disable splitting of HepMC output file:',
			'  #FILE_SIZE = 1000000000',
			'  ',
			'  # Makes particles with c*tau > 10 mm stable:',
			'  MAX_PROPER_LIFETIME = 10.0',
			'}(run)',
			'(beam){',
			'  BEAM_1 =  2212; BEAM_ENERGY_1 = 3500.;',
			'  BEAM_2 =  2212; BEAM_ENERGY_2 = 3500.;',
			'}(beam)',
			'(processes){',
			'  Process 93 93 -> 93 93',
			'  Order_EW 0',
			'  End process',
			'}(processes)',
			'(selector){',
			'  # To be as inclusive as possible, the pT cut has been lowered to the',
			'  # same value as in the multiple parton interactions.',
			'  # Note that this pT cut has to be adjusted if E_CMS is changed,',
			'  # such that it is never lower then',
			'  #   pT_min = SCALE_MIN*(E_CMS/1800)^RESCALE_EXPONENT',
			'  # in the multiple parton interactions.',
			'  # Parameters of tuned MPI cut-off for cteq66 (the default PDF):',
			'  #   SCALE_MIN = 2.63',
			'  #   RESCALE_EXPONENT = 0.192',
			'  NJetFinder  2  2.63*pow(E_CMS/1800,0.192)  0.0  1.0',
			'  # Use this for hard leading jets in a certain mass window',
			'  Mass 93 93 0 7000 ',
			'}(selector)',
			'(me){',
			'  ME_SIGNAL_GENERATOR = Comix',
			'}(me)',
			'(mi){',
			'  MI_HANDLER = Amisic',
			'}(mi)'
 		)
	)
)
